import streamlit as st

# # Access secrets
# testing_mode = st.secrets["testing_mode"]
# payment_provider = st.secrets["payment_provider"]
testing_mode = false
payment_provider = "stripe" 

# stripe_api_key = st.secrets["stripe_api_key"]
# stripe_link = st.secrets["stripe_link"]
stripe_api_key = "stripe_api_key" 
stripe_link = "stripe_link"  

client_id = st.secrets["client_id"]
client_secret = st.secrets["client_secret"]
# client_id = "Google_client_id you can get by using google auth2"
# client_secret = "Google_client_secret you can get by using google auth2"

# redirect_url = st.secrets["redirect_url"]
redirect_url = 'http://localhost:8501/'

# Print to confirm they're loaded correctly (optional)
st.write(f"Testing mode: {testing_mode}")
st.write(f"Payment Provider: {payment_provider}")
