import streamlit as st
import os

# # Access secrets
# testing_mode = st.secrets["testing_mode"]
# payment_provider = st.secrets["payment_provider"]
testing_mode = false
payment_provider = "stripe" 

# stripe_api_key = st.secrets["stripe_api_key"]
# stripe_link = st.secrets["stripe_link"]
stripe_api_key = "stripe_api_key" 
stripe_link = "stripe_link"  

client_id = st.secrets["client_id"]
client_secret = st.secrets["client_secret"]
# client_id = "239686786821-jrj2mn82nbbm5smrb5gbh2bh1obvgok6.apps.googleusercontent.com"
# client_secret = "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"

# redirect_url = st.secrets["redirect_url"]
redirect_url = 'http://localhost:8501/'

# Print to confirm they're loaded correctly (optional)
st.write(f"Testing mode: {testing_mode}")
st.write(f"Payment Provider: {payment_provider}")
